# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://liv2.firebaseapp.com/
title: LiveIntent
email: info@liveintent.com
author: LiveIntent @ gdubow
description: > # "LiveIntent is a smarter way to market to people, not pixels.
copyright: 'Copyright &copy; 2016 LiveIntent. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

