# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://liveintent.com 
title: LiveIntent
email: info@liveintent.com
author: LiveIntent @ gdubow
description: > # A smarter way to market and advertise in email.
copyright: 'Copyright &copy; 2016 LiveIntent. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

