- position: Senior Product Manager - Demand Side Platform 
  link: http://app.jobvite.com/m?3UmdThw8
  location: New York, NY

- position: VP, Product - Supply Side Platform
  link: http://app.jobvite.com/m?3fodThwv
  location: New York, NY

- position: VP, Product - Demand Side Platform
  link: http://app.jobvite.com/m?3vpdThwM
  location: New York, NY