- position: Senior Product Manager - Demand Side Platform 
  link: http://app.jobvite.com/m?3UmdThw8
  location: New York, NY

- position: Senior Techincal Product Manager
  link: http://app.jobvite.com/m?3CnaWiwS
  location: New York, NY

- position: Director, Product - Supply Side Platform
  link: http://app.jobvite.com/m?3fodThwv
  location: New York, NY